export const ADD_NEW_BANNER = "ADD_NEW_BANNER";

export const ADD_NEW_RECOMMEND = "ADD_NEW_RECOMMEND";

export const ADD_NEW_POPULAR = "ADD_NEW_POPULAR";

export const ADD_NEW_QUERY_SEARCH = "ADD_NEW_QUERY_SEARCH";

export const ADD_NEW_DATA_SEARCH = "ADD_NEW_DATA_SEARCH";
