// Home Page
export const ADD_NEW_BANNER = "ADD_NEW_BANNER";

export const ADD_NEW_RECOMMEND = "ADD_NEW_RECOMMEND";

export const ADD_NEW_POPULAR = "ADD_NEW_POPULAR";

// Product Page
export const ADD_NEW_DATA_SIDEBAR = "ADD_NEW_DATA_SIDEBAR";

export const ADD_NEW_FILTER_QUERY_PARAM = "ADD_NEW_FILTER_QUERY_PARAM";

export const ADD_NEW_SORT_QUERY_PARAM = "ADD_NEW_SORT_QUERY_PARAM";

export const GET_MAIN_TITLE_FILTER_PRODUCT = "GET_MAIN_TITLE_FILTER_PRODUCT";
